import {Ionicons} from '@expo/vector-icons';
import {useLocalSearchParams, router} from 'expo-router';
import React, {useState} from 'react';
import {Alert, Dimensions, Image, Linking, Modal, Platform, Pressable, ScrollView, Share, StyleSheet, Text, View} from 'react-native';
import MapView, {Marker} from 'react-native-maps';
import {SafeAreaView} from 'react-native-safe-area-context';
import {spotImage} from '@/components/SpotCard';
import {Card, Chip, IconButton, Muted, PrimaryButton, Screen, SectionTitle} from '@/components/ui';
import {useApp} from '@/store/AppContext';
import {colors, radius, spacing} from '@/theme';

export default function SpotDetail(){
  const {id}=useLocalSearchParams<{id:string}>();const app=useApp();const spot=app.spots.find(x=>x.id===id);const [safety,setSafety]=useState(false);
  if(!spot)return <Screen><Muted>This spot is no longer available.</Muted></Screen>;
  const liked=app.likes.some(x=>x.spot_id===spot.id),saved=app.saves.some(x=>x.spot_id===spot.id&&x.list==='saved'),been=app.saves.some(x=>x.spot_id===spot.id&&x.list==='beenThere');const myRating=app.ratings.find(x=>x.spot_id===spot.id)?.stars??0;const publicRatings=spot.ratings??[];const average=publicRatings.length?publicRatings.reduce((a,x)=>a+x.stars,0)/publicRatings.length:spot.rating;
  const requireAccount=(action:()=>void)=>app.session?action():router.push('/(tabs)/profile'); const directions=()=>{const label=encodeURIComponent(spot.title),point=`${spot.latitude},${spot.longitude}`;Linking.openURL(Platform.OS==='ios'?`http://maps.apple.com/?ll=${point}&q=${label}`:`https://www.google.com/maps/search/?api=1&query=${point}`)};
  const photos=spot.photo_urls?.length?spot.photo_urls.map(uri=>({uri})): [spotImage(spot)];
  return <View style={styles.screen}><ScrollView contentContainerStyle={{paddingBottom:80}}><ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false}>{photos.map((source,index)=><Image key={index} source={source} style={styles.hero}/>)}</ScrollView><SafeAreaView edges={['top']} style={styles.nav}><IconButton label="Back" icon="chevron-back" onPress={()=>router.back()}/><View style={styles.navRight}><IconButton label="Share" icon="share-outline" onPress={()=>Share.share({message:spot.is_public?`${spot.title}\n${spot.address}`:`${spot.title}\nPrivate Circle spot — only current members can view the location in GetOut.`})}/><IconButton label="More" icon="ellipsis-horizontal" onPress={()=>setSafety(true)}/></View></SafeAreaView>
    <View style={styles.body}><View style={styles.audience}><Ionicons name={spot.is_public?'earth':'lock-closed'} size={13} color={spot.is_public?colors.orange:colors.green}/><Text style={styles.audienceText}>{spot.is_public?(spot.circle_ids.length?'Public + Circles':'Public'):'Circle only'}</Text></View><Text style={styles.title}>{spot.title}</Text><Muted>{[spot.neighborhood,spot.city].filter(Boolean).join(', ')}</Muted><View style={styles.meta}><Ionicons name="star" size={17} color={colors.orange}/><Text style={styles.metaText}>{average?average.toFixed(1):'Not rated'}</Text><Muted>· {publicRatings.length} review{publicRatings.length===1?'':'s'}</Muted></View>
      <Card style={styles.rating}><Text style={styles.label}>{myRating?`Your rating: ${myRating} of 5`:'Rate this spot'}</Text><View style={styles.stars}>{[1,2,3,4,5].map(value=><Pressable key={value} accessibilityLabel={`${value} stars`} onPress={()=>requireAccount(()=>app.setRating(spot.id,value===myRating?0:value))}><Ionicons name={value<=myRating?'star':'star-outline'} size={31} color={colors.orange}/></Pressable>)}</View><Muted>Tap your selected star again to clear your rating.</Muted></Card>
      <View style={styles.actionRow}><Action icon={liked?'heart':'heart-outline'} label={liked?'Loved':'Love'} active={liked} onPress={()=>requireAccount(()=>app.toggleLike(spot.id))}/><Action icon={saved?'bookmark':'bookmark-outline'} label="Save" active={saved} onPress={()=>requireAccount(()=>app.toggleSave(spot.id,'saved'))}/><Action icon={been?'checkmark-circle':'checkmark-circle-outline'} label="Been" active={been} onPress={()=>requireAccount(()=>app.toggleSave(spot.id,'beenThere'))}/></View>
      <SectionTitle>About this spot</SectionTitle><Text style={styles.details}>{spot.details||'No description was provided for this spot.'}</Text><View style={styles.tags}>{spot.tags.map(tag=><Chip key={tag} label={`#${tag}`}/>)}</View>
      <SectionTitle>Location</SectionTitle><MapView scrollEnabled={false} pitchEnabled={false} style={styles.map} initialRegion={{latitude:spot.latitude,longitude:spot.longitude,latitudeDelta:.012,longitudeDelta:.012}}><Marker coordinate={spot}/></MapView><Muted>{spot.address||`${spot.latitude.toFixed(5)}, ${spot.longitude.toFixed(5)}`}</Muted><PrimaryButton title="Get Directions" icon="navigate" onPress={directions}/>
      {spot.profiles&&<><SectionTitle>Shared by</SectionTitle><Card style={styles.owner}><View style={styles.ownerAvatar}><Ionicons name="person" size={24} color={colors.muted}/></View><View><Text style={styles.label}>{spot.profiles.display_name}</Text><Muted>@{spot.profiles.username}</Muted></View></Card></>}
    </View></ScrollView>
    <Modal visible={safety} transparent animationType="fade" onRequestClose={()=>setSafety(false)}><Pressable style={styles.backdrop} onPress={()=>setSafety(false)}><Card style={styles.menu}><Text style={styles.label}>Safety options</Text>{['spam','inappropriate','unsafeLocation','other'].map(reason=><Pressable key={reason} onPress={()=>requireAccount(()=>app.reportSpot(spot,reason).then(()=>{setSafety(false);Alert.alert('Report sent','Thanks for helping keep GetOut safe.')}))} style={styles.menuRow}><Text style={styles.menuText}>Report: {reason}</Text></Pressable>)}{app.profile?.id!==spot.owner_id&&<Pressable onPress={()=>requireAccount(()=>app.blockUser(spot.owner_id).then(()=>{setSafety(false);router.back()}))} style={styles.menuRow}><Text style={styles.danger}>Block @{spot.profiles?.username}</Text></Pressable>}</Card></Pressable></Modal>
  </View>
}
function Action({icon,label,active,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;active?:boolean;onPress():void}){return <Pressable onPress={onPress} style={styles.action}><Ionicons name={icon} size={23} color={active?colors.green:colors.text}/><Text style={[styles.actionText,active&&{color:colors.green}]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},hero:{width:Dimensions.get('window').width,height:430},nav:{position:'absolute',left:spacing.md,right:spacing.md,top:0,flexDirection:'row',justifyContent:'space-between'},navRight:{flexDirection:'row',gap:spacing.sm},body:{padding:spacing.lg,gap:spacing.md},audience:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:5,backgroundColor:colors.surface2,borderRadius:radius.pill,paddingHorizontal:10,paddingVertical:6},audienceText:{color:colors.text,fontSize:12,fontWeight:'800'},title:{fontFamily:'serif',fontSize:34,fontWeight:'800',color:colors.cream},meta:{flexDirection:'row',alignItems:'center',gap:5},metaText:{color:colors.text,fontWeight:'800'},rating:{padding:spacing.md,gap:spacing.sm},label:{color:colors.text,fontSize:16,fontWeight:'700'},stars:{flexDirection:'row',justifyContent:'space-between'},actionRow:{flexDirection:'row',justifyContent:'space-between'},action:{width:70,alignItems:'center',gap:6,paddingVertical:12,borderRadius:radius.control,backgroundColor:colors.surface},actionText:{fontSize:12,color:colors.text,fontWeight:'700'},details:{color:colors.text,fontSize:16,lineHeight:24},tags:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},map:{height:210,borderRadius:radius.card},owner:{padding:spacing.md,flexDirection:'row',alignItems:'center',gap:12},ownerAvatar:{width:48,height:48,borderRadius:24,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},modalHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},link:{color:colors.green,fontWeight:'800'},trip:{padding:spacing.md,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.7)',justifyContent:'flex-end',padding:spacing.lg},menu:{padding:spacing.md},menuRow:{paddingVertical:15,borderBottomColor:colors.faint,borderBottomWidth:StyleSheet.hairlineWidth},menuText:{color:colors.text},danger:{color:colors.red,fontWeight:'700'}});
