import {Ionicons} from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Linking from 'expo-linking';
import React, {useEffect, useState} from 'react';
import {Alert, Pressable, StyleSheet, Switch, Text, View} from 'react-native';
import {Card, Muted, Screen, SectionTitle} from '@/components/ui';
import {useApp} from '@/store/AppContext';
import {colors, spacing} from '@/theme';

const legalKey='privacy.hasConfirmedCannabisLegalAge';
export default function Settings(){const app=useApp();const [legal,setLegal]=useState(false);useEffect(()=>{AsyncStorage.getItem(legalKey).then(v=>setLegal(v==='true'))},[]);const toggle=(v:boolean)=>{setLegal(v);AsyncStorage.setItem(legalKey,String(v))};const link=(title:string,url:string)=><Pressable onPress={()=>Linking.openURL(url)} style={styles.row}><Text style={styles.rowText}>{title}</Text><Ionicons name="open-outline" size={18} color={colors.muted}/></Pressable>;
return <Screen><SectionTitle>Account</SectionTitle><Card><View style={styles.row}><Text style={styles.rowText}>Sign-in</Text><Muted>Apple or Google</Muted></View>{app.profile&&<View style={styles.row}><Text style={styles.rowText}>GetOut profile</Text><Muted>@{app.profile.username}</Muted></View>}<Muted style={styles.copy}>Your profile and private data are tied to your signed-in account and can be restored on another device.</Muted><Pressable onPress={()=>Alert.alert('Sign out of GetOut?','Your synced data stays in Supabase.',[{text:'Cancel'},{text:'Sign Out',style:'destructive',onPress:app.signOut}])} style={styles.row}><Text style={styles.action}>Sign Out</Text></Pressable><Pressable onPress={()=>Alert.alert('Delete your GetOut profile and data?','This removes your public profile, public spots, and private GetOut data.',[{text:'Cancel'},{text:'Delete',style:'destructive',onPress:()=>app.deleteAccount().catch(e=>Alert.alert('Could not delete',String(e)))}])} style={styles.row}><Text style={styles.danger}>Delete Profile & GetOut Data</Text></Pressable></Card>
<SectionTitle>Cannabis content</SectionTitle><Card style={styles.copy}><View style={styles.switchRow}><Text style={styles.rowText}>I confirm I am of legal age</Text><Switch value={legal} onValueChange={toggle} trackColor={{true:colors.green}}/></View><Muted>Weed-friendly content is shown only when location access confirms you are in Canada or California. GetOut does not facilitate cannabis sales.</Muted></Card>
<SectionTitle>Blocked people</SectionTitle><Card>{!app.blocks.length?<Muted style={styles.copy}>No blocked people.</Muted>:app.blocks.map(b=><View key={b.id} style={styles.row}><Muted>Account …{b.blocked_user_id.slice(-8)}</Muted><Pressable onPress={()=>app.unblockUser(b.blocked_user_id)}><Text style={styles.action}>Unblock</Text></Pressable></View>)}</Card>
<SectionTitle>Permissions</SectionTitle><Card><Pressable onPress={()=>Linking.openSettings()} style={styles.row}><Text style={styles.rowText}>Open app settings</Text><Ionicons name="settings-outline" size={18} color={colors.muted}/></Pressable><Muted style={styles.copy}>Location powers nearby discovery and legal-jurisdiction checks.</Muted></Card>
<SectionTitle>About</SectionTitle><Card><View style={styles.row}><Text style={styles.rowText}>Version</Text><Muted>0.1</Muted></View>{link('Privacy Policy','https://parthdhroovji.me/GetOut')}{link('Terms & Community Guidelines','https://parthdhroovji.me/GetOut/terms')}{link('Support & Safety','mailto:parthdhroovji1@gmail.com')}</Card></Screen>}
const styles=StyleSheet.create({row:{minHeight:52,paddingHorizontal:spacing.md,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.faint},rowText:{color:colors.text,fontWeight:'600'},copy:{padding:spacing.md},switchRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:8},action:{color:colors.green,fontWeight:'700'},danger:{color:colors.red,fontWeight:'700'}});
