import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import React, {useMemo, useRef, useState} from 'react';
import {Image, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import MapView, {Marker, PROVIDER_GOOGLE} from 'react-native-maps';
import {SafeAreaView} from 'react-native-safe-area-context';
import {spotImage} from '@/components/SpotCard';
import {useLocation} from '@/hooks/useLocation';
import {distanceMeters} from '@/lib/geo';
import {useApp} from '@/store/AppContext';
import {colors, radius, spacing} from '@/theme';

const NYC = {latitude: 40.7128, longitude: -74.006, latitudeDelta: .13, longitudeDelta: .13};
export default function ExploreMap() {
  const {spots, saves, circles} = useApp(); const {location, request} = useLocation(); const map = useRef<MapView>(null); const [selected, setSelected] = useState<string>(); const [source, setSource] = useState('all');
  const mappable = useMemo(() => spots.filter(spot => spot.latitude && spot.longitude && (source === 'all' || (source === 'public' ? spot.is_public : spot.circle_ids.includes(source)))), [spots, source]); const saved = useMemo(() => mappable.filter(s => saves.some(v => v.spot_id === s.id && v.list === 'saved') && (!location || distanceMeters(location, s) <= 25_000)), [mappable, saves, location]);
  const center = async () => { const current = await request(); if (current) map.current?.animateToRegion({...current, latitudeDelta: .06, longitudeDelta: .06}); };
  return <SafeAreaView style={styles.screen} edges={['top']}><MapView ref={map} provider={process.env.EXPO_OS === 'android' ? PROVIDER_GOOGLE : undefined} style={StyleSheet.absoluteFill} initialRegion={location ? {...location, latitudeDelta: .1, longitudeDelta: .1} : NYC} showsUserLocation>
      {mappable.map(spot => <Marker key={spot.id} coordinate={spot} title={spot.title} pinColor={saves.some(x => x.spot_id === spot.id) ? colors.green : spot.is_public ? colors.orange : colors.purple} onPress={() => setSelected(spot.id)}/>) }
    </MapView>
    <View pointerEvents="box-none" style={StyleSheet.absoluteFill}><SafeAreaView pointerEvents="box-none" style={styles.overlay} edges={['top']}><View style={styles.titleRow}><Text style={styles.title}>Explore</Text><Pressable style={styles.locate} onPress={center}><Ionicons name="locate" size={22} color={colors.text}/></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{[{id:'all',name:'All',icon:'layers'},{id:'public',name:'Public',icon:'earth'},...circles.map(circle=>({id:circle.id,name:circle.name,icon:'people'}))].map(item=>{const active=source===item.id;return <Pressable key={item.id} onPress={()=>{setSource(item.id);setSelected(undefined)}} style={[styles.filter,active&&styles.filterActive]}><Ionicons name={item.icon as never} size={15} color={active?colors.text:colors.muted}/><Text style={[styles.filterText,active&&styles.filterTextActive]}>{item.name}</Text></Pressable>})}</ScrollView><View style={{flex: 1}}/>
      {!!saved.length && <View><Text style={styles.savedTitle}><Ionicons name="bookmark"/> Saved nearby</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.savedRow}>{saved.map(spot => <Pressable key={spot.id} onPress={() => router.push(`/spot/${spot.id}`)} style={styles.mini}><Image source={spotImage(spot)} style={styles.miniImage}/><View style={styles.miniInfo}><Text numberOfLines={1} style={styles.miniTitle}>{spot.title}</Text><Text style={styles.miniSubtitle}>{spot.neighborhood || 'Saved spot'}</Text></View></Pressable>)}</ScrollView></View>}
      {selected && mappable.some(spot=>spot.id===selected) && <Pressable onPress={() => router.push(`/spot/${selected}`)} style={styles.callout}><Image source={spotImage(mappable.find(s => s.id === selected)!)} style={styles.calloutImage}/><View style={{flex: 1}}><Text style={styles.miniTitle}>{mappable.find(s => s.id === selected)?.title}</Text><Text style={styles.miniSubtitle}>{mappable.find(s => s.id === selected)?.is_public?'Public spot':'Private Circle spot'} · {mappable.find(s => s.id === selected)?.neighborhood}</Text></View><Ionicons name="chevron-forward" size={22} color={colors.muted}/></Pressable>}
    </SafeAreaView></View>
  </SafeAreaView>;
}
const styles = StyleSheet.create({screen: {flex: 1, backgroundColor: colors.background}, overlay: {flex: 1, paddingBottom: 90}, titleRow: {zIndex: 2, marginHorizontal: spacing.lg, marginTop:spacing.lg,marginBottom:spacing.sm, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'}, title: {fontFamily: 'serif', fontSize: 34, fontWeight: '700', color: colors.cream, textShadowColor: '#000', textShadowRadius: 8}, locate: {width: 44, height: 44, borderRadius: 22, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center'},filters:{paddingHorizontal:spacing.lg,gap:spacing.sm},filter:{height:38,paddingHorizontal:13,borderRadius:19,backgroundColor:'rgba(27,27,30,.92)',borderWidth:StyleSheet.hairlineWidth,borderColor:'rgba(255,255,255,.14)',flexDirection:'row',alignItems:'center',gap:6},filterActive:{backgroundColor:colors.green,borderColor:colors.green},filterText:{color:colors.muted,fontSize:13,fontWeight:'700'},filterTextActive:{color:colors.text}, savedTitle: {color: colors.text, fontWeight: '800', marginHorizontal: spacing.lg, marginBottom: spacing.sm}, savedRow: {paddingHorizontal: spacing.lg, gap: spacing.sm}, mini: {width: 205, flexDirection: 'row', borderRadius: radius.control, overflow: 'hidden', backgroundColor: colors.surface}, miniImage: {width: 70, height: 70}, miniInfo: {flex: 1, justifyContent: 'center', padding: 10}, miniTitle: {color: colors.text, fontWeight: '700'}, miniSubtitle: {color: colors.muted, fontSize: 12, marginTop: 3}, callout: {margin: spacing.lg, padding: spacing.sm, borderRadius: radius.card, backgroundColor: colors.surface, flexDirection: 'row', alignItems: 'center', gap: 12}, calloutImage: {width: 64, height: 64, borderRadius: 14}});
